package com.readwise.ai.model

/**
 * Supported AI service providers
 */
enum class AIProvider(val displayName: String, val defaultBaseUrl: String?) {
    OPENAI("OpenAI", "https://api.openai.com/v1"),
    CLAUDE("Anthropic Claude", "https://api.anthropic.com"),
    GEMINI("Google Gemini", "https://generativelanguage.googleapis.com/v1"),
    DEEPSEEK("DeepSeek", "https://api.deepseek.com"),
    CUSTOM("Custom API", null)
}

/**
 * AI service type for feature routing
 */
enum class AIServiceType {
    CHAT,           // General chat interface
    SUMMARIZATION,   // Chapter/book summarization
    X_RAY,          // Character/term analysis
    TRANSLATION,     // Text translation
    EXPLANATION,     // Concept explanation
    VOCABULARY       // Word lookup and explanation
}

/**
 * Message role in chat conversation
 */
enum class MessageRole {
    SYSTEM,
    USER,
    ASSISTANT
}

/**
 * Chat message in conversation
 */
data class ChatMessage(
    val role: MessageRole,
    val content: String,
    val timestamp: Long = System.currentTimeMillis()
)

/**
 * AI response with metadata
 */
data class AIResponse(
    val content: String,
    val model: String,
    val tokensUsed: Int? = null,
    val finishReason: String? = null,
    val latency: Long = 0 // milliseconds
)

/**
 * Chapter summary generated by AI
 */
data class ChapterSummary(
    val bookId: String,
    val chapterIndex: Int,
    val chapterTitle: String?,
    val summary: String,
    val keyPoints: List<String>,
    val importantQuotes: List<String>? = null,
    val generatedAt: Long = System.currentTimeMillis(),
    val aiModel: String
)

/**
 * X-ray entity (character, location, term, etc.)
 */
data class XRayEntity(
    val id: String,
    val bookId: String,
    val type: XRayEntityType,
    val name: String,
    val description: String,
    val firstMention: Int, // chapter index
    val mentions: List<Int>, // chapter indices where appears
    val relatedEntities: List<String> = emptyList(), // IDs of related entities
    val metadata: Map<String, String> = emptyMap() // Additional data
)

/**
 * Types of entities in X-ray
 */
enum class XRayEntityType {
    CHARACTER,
    LOCATION,
    TERM,
    ORGANIZATION,
    EVENT,
    CONCEPT,
    OTHER
}

/**
 * X-ray analysis result for entire book
 */
data class XRayData(
    val bookId: String,
    val entities: List<XRayEntity>,
    val relationships: Map<String, List<String>> = emptyMap(), // entity ID -> related entity IDs
    val generatedAt: Long = System.currentTimeMillis(),
    val isComplete: Boolean = false
)

/**
 * Vocabulary entry
 */
data class VocabularyEntry(
    val word: String,
    val definition: String,
    val partOfSpeech: String? = null,
    val example: String? = null,
    val synonyms: List<String>? = null,
    val context: String? = null, // Sentence where word appeared
    val frequency: Int = 1
)

/**
 * AI request configuration
 */
data class AIRequestConfig(
    val provider: AIProvider,
    val model: String,
    val temperature: Float = 0.7f,
    val maxTokens: Int = 2000,
    val topP: Float? = null,
    val frequencyPenalty: Float? = null,
    val presencePenalty: Float? = null
)
