#!/bin/sh

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#       (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then to run this script, type that shell name before the whole
#       command line, like:
#
#           ksh Gradle
#
#       Busybox and similar reduced shells will NOT work, because this script
#       requires all of these POSIX shell features:
#         * functions;
#         * expansions «$var», «${var}», «${var:-default}», «${var+SET}»,
#           «${var#prefix}», «${var%suffix}», and «$( cmd )»;
#         * compound commands having a testable exit status, especially «case»;
#         * various built-in commands including «command», «set», and «ulimit».
#
#       Important for patching:
#
#       (2) This script targets any POSIX shell, so it avoids extensions provided
#       by Bash, Ksh, etc; in particular arrays are avoided.
#
#       The "traditional" practice of packing multiple parameters into a
#       space-separated string is a well documented source of bugs and security
#       problems, so this is (mostly) avoided, by progressively accumulating
#       options in "$@", and finally passing that to Java.
#
#       Where the inherited environment variables (DEFAULT_JVM_OPTS, JAVA_OPTS,
#       and GRADLE_OPTS) rely on word-splitting, this is performed explicitly;
#       see the in-line comments for details.
#
#       There are tweaks for specific operating systems such as AIX, CygWin,
#       Darwin, MinGW, and NonStop.
#
#       (3) This script is generated from the Groovy template
#       https://github.com/gradle/gradle/blob/HEAD/subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt
#       within the Gradle project.
#
#       You can find Gradle at https://github.com/gradle/gradle/.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

while [ -h "$app_path" ]; do
    # Need to resolve symlinks first
    ls=$(ls -ld "$app_path")
    link=$(expr "$ls" : '.*-> \(.*\)$' | cut -f2 -d ' ')
    if [ -z "$link" ]; then
        # Not a symlink
        app_home=$(dirname "$app_path")
        break
    fi
    app_path=$link
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
APP_HOME=$(dirname "${app_path}")
# shellcheck disable=SC2166
APP_HOME=$(cd "${APP_HOME}/.." && pwd)

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD="maximum"

warn () {
    echo "$*"
} >&2
}

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in
  CYGWIN* )
    cygwin=true
    ;;
  Darwin* )
    darwin=true
    ;;
  MINGW* | MSYS* | MINGW* )
    msys=true
    ;;
  NONSTOP* )
    nonstop=true
    ;;
esac

# Determine the Java command to use to start the JVM.
if [ -n "${JAVA_HOME:-}" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1 ; then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    MAX_FD_LIMIT=$(ulimit -H -n)
    if [ $? -eq 0 ] ; then
        if [ "$MAX_FD_LIMIT" = "maximum" ] || [ "$MAX_FD_LIMIT" = "max" ] ; then
            MAX_FD=$MAX_FD_LIMIT
        else
            # shellcheck disable=SC2015
            if [ "$MAX_FD_LIMIT" -ge 65536 ] ; then
                MAX_FD=65536
            else
                MAX_FD=$((MAX_FD_LIMIT-512))
            fi
        fi
    else
        warn "Could not query maximum open file descriptor"
    fi
fi

# For Darwin, add options to specify how the application appears in the dock
if "$darwin"; then
    GRADLE_OPTS="$GRADLE_OPTS \"-Xdock:name=$APP_BASE_NAME\" \"-Xdock:icon=$APP_HOME/media/gradle.icns\""
fi

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" ; then
    APP_HOME=$(cygpath --path --mixed "$APP_HOME")
    CLASSPATH=$(cygpath --path --mixed "$CLASSPATH")
    JAVACMD=$(cygpath --path --mixed "$JAVACMD")
    # We build the pattern for arguments to be converted to cygwin/MSYS paths.
    CP=$(echo "$CLASSPATH" | sed 's/:/;/g')
    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    for arg do
        # shellcheck disable=SC2015
        if [ -n "$arg" ]; then
            CP="$CP;$arg"
        fi
    done
    # shellcheck disable=SC2015
    CLASSPATH=$(echo "$CP" | sed 's/;/;/g')
fi

# For MinGW, ensure paths are in Unix format before running java
if "$msys" ; then
    APP_HOME=$(cd "${APP_HOME}" && pwd -W)
    CLASSPATH=$(cd "${CLASSPATH}" && pwd -W | tr '\\' /)
    JAVACMD=$(cd "$(dirname "$JAVACMD")" && pwd -W)/$(basename "$JAVACMD")
fi

# For NonStop, ensure paths are in Unix format before running java
if "$nonstop" ; then
    APP_HOME=$(cygpath -u "$APP_HOME")
    CLASSPATH=$(cygpath -u -p "$CLASSPATH")
    JAVACMD=$(cygpath -u "$JAVACMD")
fi

# Default encoding adopted for scripts that don't specify it
if [ -z "${GRADLE_ENCODING:-}" ] ; then
    GRADLE_ENCODING=UTF-8
fi

# Collect all arguments for the java command, following the shell quoting and substitution rules
set -- %?
# Default encoding adopted for scripts that don't specify it
if [ -z "${GRADLE_ENCODING:-}" ] ; then
    GRADLE_ENCODING=UTF-8
fi

# Collect all arguments for the java command
set --


# Append JAVA_OPTS to avoid quoting issues when passing them
# shellcheck disable=SC2153
eval set -- "$@" ${JAVA_OPTS:-}" "${DEFAULT_JVM_OPTS:-}"

# Append GRADLE_OPTS if set
# shellcheck disable=SC2153
eval set -- "$@" ${GRADLE_OPTS:-}"

# Add application JVM and OS-specific options
# shellcheck disable=SC2015
if [ -n "$JAVA_OPTS" ] ; then
    # For Java_home, JAVA_OPTS should already be in JVM options
    if [ -n "${JAVA_HOME:-}" ] && [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        warn "JAVA_OPTS should not be specified when using a JDK included in JAVA_HOME"
    fi
fi

# Collect JVM arguments from other sources
if [ -n "${GRADLE_JVM_OPTS:-}" ]; then
    # shellcheck disable=SC2153
    eval set -- "$@" ${GRADLE_JVM_OPTS}"
fi

# Finally, invoke the generated Gradle launcher with the collected JVM arguments and program arguments
# shellcheck disable=SC2153
exec "$JAVACMD" $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS "\"-Dorg.gradle.appname=$APP_BASE_NAME\"" -classpath "\"$APP_HOME/gradle/wrapper/gradle-wrapper.jar\"" org.gradle.wrapper.GradleWrapperMain "$@"
