#!/usr/bin/env sh

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
app_path=$0

while [ -h "$app_path" ]; do
    ls=$(ls -ld "$app_path")
    link=$(expr "$ls" : '.*-> \(.*\)$' | cut -f2 -d ' ')
    if [ -z "$link" ]; then
        app_home=$(dirname "$app_path")
        break
    fi
    app_path=$link
done

APP_HOME=$(dirname "${app_path}")
APP_HOME=$(cd "${APP_HOME}/.." && pwd)

# Determine the Java command to use to start the JVM
if [ -n "${JAVA_HOME:-}" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1 ; then
        echo "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH." >&2
        exit 1
    fi
fi

warn() {
    echo "$*" >&2
}

die() {
    echo "$*" >&2
    echo "" >&2
    exit 1
}

# Collect all arguments for the java command
set --

# Append JAVA_OPTS
eval set -- "$@" ${JAVA_OPTS:-} ${DEFAULT_JVM_OPTS:}

# Append GRADLE_OPTS
eval set -- "$@" ${GRADLE_OPTS:}

# Collect JVM options
if [ -n "${GRADLE_JVM_OPTS:-}" ]; then
    eval set -- "$@" ${GRADLE_JVM_OPTS}
fi

# Invoke Gradle
exec "$JAVACMD" \
  -Dorg.gradle.appname=Gradle \
  -classpath "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" \
  org.gradle.wrapper.GradleWrapperMain \
  "$@"
